prestacao = float(input("informe o valor da prestação: "))
taxa = float(input("informe a taxa de juros mensal: "))
tempo = int(input("informe a quantidade de juros mensal: "))
valor_final = prestacao+(prestacao*taxa/100*tempo)
print(f"O valor em atraso será de R$ {valor_final: .2f}")